# https://geshan.com.np/blog/2021/12/docker-postgres/

version: '3.9'

services:
  web:
    build: ./web
    depends_on:
      - database
    ports:
      - '4440:3000'
    env_file:
      - .env
  dash:
    depends_on:
      - database
    ports:
      - 4441:3000
    build: ./dash
    env_file:
      - .env
  deno:
    container_name: deno
    image: deno
    restart: always
    build: embed-service/
    env_file:
      - .env
    ports:
      - '4442:3000'
  backend:
    build: .
    depends_on:
      - database
    ports:
      - '4443:3000'
    env_file:
      - .env
  database:
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
