# https://geshan.com.np/blog/2021/12/docker-postgres/

version: '3.9'

services:
  web:
    build: ./web
    depends_on:
      - database
    ports:
      - '890:3000'
    env_file:
      - .env
  dash:
    depends_on:
      - database
    ports:
      - 3400:3000
    build: ./dash
    env_file:
      - .env

  backend:
    build: .
    depends_on:
      - database
    ports:
      - '850:7878'
    env_file:
      - .env
  database:
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  # db:
  #     image: postgres
  #     restart: always
  #     ports:
  #         - "5432:5432"
  #     environment:
  #         POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  # adminer:
  #     image: adminer
  #     restart: always
  #     ports:
  #         - 8080:8080
volumes:
  db:
    driver: local
