[package]
name = "tsunami"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ascella"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.1"
actix-multipart = "0.4.0"
actix-web = "4"
anyhow = "1.0.56"
async-trait = "0.1.52"
base64 = "0.13.0"
byte-unit = "4.0.13"
bytes = "1.1.0"
cached = "0.26.2"
chrono = "0.4.19"
dotenv = "0.15.0"
futures = "0.3.19"
governor = "0.4.2"
http = "0.2.6"
humantime = "2.1.0"
image = "0.24.1"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.9.0"
openssl = { version = "0.10.38", optional = true }
paperclip = { git = "https://github.com/fritterhoff/paperclip", features = ["actix4", "actix-multipart"] }
parking_lot = "0.12.0"
rand = "0.8.5"
reqwest = { version = "0.11.8", features = ["json", "gzip", "brotli"] }
rust-s3 = { version = "0.28.1", features = ["with-tokio", "tokio-native-tls", "tags"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.79"
sha1 = { version = "0.6.0", features = ["std"] }
sha2 = "0.9.2"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }
tokio-cron-scheduler = "0.3.1"
tokio-pg-mapper = "0.2.0"
tokio-pg-mapper-derive = "0.2.0"
tokio-postgres = "0.7.5"
tracing = "0.1.29"
tracing-subscriber = "0.3.5"
tree_magic = "0.2.3"
ttl_cache = "0.5.1"
twilight-embed-builder = "0.8.0"
twilight-gateway = "0.8.3"
twilight-http = "0.8.4"
twilight-model = "0.8.4"
twilight-util = { version = "0.8.2", features = ["builder"] }
ulid = "0.5.0"
url = "2.2.2"

[features]
openssl-vendored = ["openssl/vendored"]
