name: Build Ascella
on:
  pull_request:
  push:

env:
  BIN_NAME: ascella
  PROJECT_NAME: ascella
  REPO_NAME: Tricked-dev/ascella

jobs:
  dist:
    name: Dist
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup | Cache
        uses: Swatinem/rust-cache@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: do funny apt install
        run: sudo apt-get install libssl-dev pkg-config libxcb-composite0-dev libx11-dev

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked

      - name: Strip release binary (linux and macos)
        run: strip "target/release/$BIN_NAME"

      - name: make dist
        run: mkdir dist

      - name: Build archive
        shell: bash
        run: cp "target/release/$BIN_NAME" "dist/"

      - name: Build archive
        shell: bash
        run: cp "target/release/desktop" "dist/"

      - uses: actions/upload-artifact@v2.2.4
        with:
          name: ascella-x86_64-unknown-linux-gnu
          path: dist
